- lib/internet.js
Tiny fix for internet/color algorithm. Seems to be there was small copy-paste issue.
@Marak
> Fixed color copy-paste

- CONTRIBUTING.md
Including [CONTRIBUTING.md](CONTRIBUTING.md) into upcoming release
> added CONTRIBUTING.md file for better community contribution #170

- Readme.md
- build/src/docs.md
adding badge fury, thanks to @troy0820
> added badge fury #177

- MIT-LICENSE.txt
- Readme.md
- build/gulpfile.js
- build/src/docs.md
I have re-made all contents of #200 including docs sources and gulpfile.
> updated readme: sources and generated content #170

- lib/internet.js
- test/internet.unit.js
> Add internet.url()

- index.js
- lib/address.js
Added missing street prefix method (usefull for French addresses at least).
> Added missing street prefix method

- Readme.md
- index.js
- lib/commerce.js
- lib/internet.js
- lib/locales/en.js
- package.json
- test/all.functional.js
- test/commerce.unit.js
- test/random.unit.js
Implements the commerce functionality from the Ruby implementation. Also updates the API documentation to show examples of functions and there uses.
> Commerce implementation

- index.js
- lib/locales/ru.js
- lib/name.js
This pull request will fix a few problems related to Russian locale:
- `faker.name.firstName()` returns English name
- `faker.name.lastName()` fails because of misprinted `defintions` https://github.com/Marak/faker.js/blob/master/lib/name.js#L20
- `faker.name.findName()` randomly returns male first and female last names and vice verca
In addition, all of these functions will accept `gender` argument.
> Support gender in names

- Readme.md
In addition to #252. Totally forgot it.
> List Greek support to Readme.md

- lib/internet.js
- test/internet.unit.js
Proposed fix for https://github.com/Marak/faker.js/issues/283 and https://github.com/Marak/faker.js/issues/294.
> Prevent apostrophes in return value of internet#domainWords

- lib/name.js
Mr Jane Smith is ok, but could be better.
> adjust method to allow for gender based prefixes

- lib/finance.js
- lib/random.js
- test/finance.unit.js
Bitcoin support as requested in issue #285
I wasn't 100% sure on where to apply it. Bitcoin is mostly finance as it's a currency but you could also argue it belongs in internet as it's a 100% internet based service.
Up to discussion...
> Bitcoin support

- lib/finance.js
- test/finance.unit.js
* Use faker.random.number
* Fix range. Range was 27 - 36. Should be 27 - 34. Was causing tests to fail.
> bitcoinAddress fix

- lib/hacker.js
hacker.phrase repeats the same string for each lexical type. This commit passes functions instead of strings to faker.helpers.mustache to generate a new random string for each instance. Minor, but hacker.phrase is fun and this reduces repetition in the resulting phrase.
> hacker.phrase - generate random string for each lexical instance

- lib/commerce.js
Remove "max" and "fixedAmount" arguments from the faker.commerce.department method
> Clean up faker.commerce.department method

- Readme.md
> Fix demo URL in Readme

- lib/helpers.js
- test/helpers.unit.js
> Prevented a crash on running helpers.shuffle on an empty array

- lib/internet.js
- test/internet.unit.js
* Returns a random 8 octet ipv6 address
> [api] Added `internet.ipv6` method

- lib/lorem.js
- test/all.functional.js
- test/lorem.unit.js
Returns a random slug for URLs
> [api] Added `lorem.slug` method

- Readme.md
Now your open collective backers and sponsors can to appear directly on your README. 
see how it'll look [here](https://github.com/apex/apex#backers)
[More info](https://github.com/opencollective/opencollective/wiki/Github-banner)
Also add badges on top.
> Add backers and sponsors from Open Collective

- lib/random.js
- test/random.unit.js
> Fix generation of float numbers

- lib/locales/de_AT/address/city_name.js
my hometown is missing. tha's a MASSIVE issue ;)
> added missing town

- Readme.md
- lib/finance.js
- lib/random.js
- test/finance.unit.js
- test/random.unit.js
Added functions to generate random hexadecimal string and ethereum address.
> Add Ethereum Address

- lib/helpers.js
- test/helpers.unit.js
Covers the case when we need to get random alphanumeric symbol
an alternative to #282
> add alphanumeric symbol * to helpers.replaceSymbols

- .gitignore
- Added the /.npm in .gitignore file
hope this will help . Waiting for your feedback . :smile:
> Added .npm in .gitignore file

- lib/random.js
- test/random.unit.js
Usage
```
faker.random.arrayElements([1,2,3]) // could be [1], [2], [3], [1, 2], ...
// optional second argument specifies number of elements to return.
faker.random.arrayElements([1,2,3], 2) // could be [1, 2], [1, 3], [2, 3].
```
> Add faker.random.arrayElements that randomly selects a subset of the given array.

- test/locales.unit.js
> Could you add test for this?
@Marak Done ✅
> Add test for setLocale function added in #488

- lib/finance.js
- test/finance.unit.js
This PR adds a generator for ABA routing numbers.
> Add ABA routing number generator

- build/src/docs.md
Added mocker-data-generator: https://github.com/danibram/mocker-data-generator
> Update Readme.md - added new module that use fakerJs

- .travis.yml
- lib/image.js
- test/image.unit.js
- Add a custom background color to image.dataUri, closes #420 
- Make data URI text aligns center and middle, it's useful because border radius won't clip it anymore.
> Add custom background color to image.dataUri

- lib/locales/es/commerce/color.js
- lib/locales/es/commerce/department.js
- lib/locales/es/commerce/index.js
- lib/locales/es/commerce/product_name.js
- lib/locales/es/index.js
Added commerce locales (color, department and product_name) to es language.
> Add commerce locale ES

- lib/random.js
From the documentation it is not clear what shape should the options object take.
> Add mixed options shape to the documentation

- lib/locales/en/finance/currency.js
- test/finance.unit.js
I double checked with https://www.iban.com/currency-codes
> Fixes currency codes

- lib/image_providers/lorempixel.js
- test/image.unit.js
It changes the protocol used by `lorempixel` to generate images.
This was discussed and requested in #652
> Changes LoremPixel from HTTP to HTTPS

- lib/locales/ar/address/street_name.js
- lib/locales/az/commerce/product_name.js
- lib/locales/cz/name/name.js
- lib/locales/es_MX/name/title.js
- lib/locales/sk/name/name.js
man -> male
woman -> female
street_preffix -> street_prefix
> Fix for some expansion key

- lib/finance.js
- test/finance.unit.js
This PR adds a `litecoinAddress` generator.
> Add litecoinAddress generator

- lib/locales/sv/commerce/product_name.js
Noticed some errors in the translation. Here's a PR :smile:
> Fixes Swedish translation for products.

- lib/locales/en/address/country_code.js
> Fix double BQ in country code for  #911

- vendor/user-agent.js
User agent currently uses Math.random() and so produces different values for the same seed.
> Make user agent deterministic

- lib/image.js
- lib/image_providers/lorempicsum.js
- package-lock.json
- test/image.unit.js
As suggested in #797 discussion, this PR adds [Lorem Picsum](https://picsum.photos/) as a faker Image Provider.
Lorem Picsum is reliable and stable, with DigitalOcean backing this project.
This can generate images in grayscale and blurred images too.
Another feature is to generate the same random image, based on a seed.
Under the namespace `lorempicsum`:
- image(width, height, grayscale, blur)
- imageGrayscaled(width, height, grayscale
- imageBlurred(width, height, blur)
- imageRandomSeeded(width, height, grayscale, blur, seed)
> Adds Lorem Picsum as image provider

- lib/locales/en/finance/currency.js
Currency symbol of turkish lira updated
https://en.wikipedia.org/wiki/Turkish_lira_sign
> Update currency symbol of turkish lira

- locale/ro.js
Added missing locale solving `Error: Cannot find module 'faker/locale/ro'` when you try to use this locale.
Thanks!
> Added missing locale/ro.js

- Readme.md
- lib/index.js
- lib/locales/en/index.js
- lib/locales/en/music/genre.js
- lib/locales/en/music/index.js
- lib/music.js
- test/music.unit.js
This is a very simple faker module at the moment that only contains a `genre` method that will return a genre of music. This would be valuable for fake data relating to some kind of music site.
I will eventually add some more methods to this module so that it can become even more useful :+1:
> Added the Music module

- lib/internet.js
- vendor/user-agent.js
Current faker instance passed into user-agent generate function to avoid loading additional locales
> Prevent all locales loading if the only one is used

- examples/node/generateMultiLevelMultiLocaleJSON.js
This example shows the generation of a multilevel company object (and JSON document) using various faker.js features
including name, address, company, date and commerce namespaces, moustache expressions and random element production. The production of randomly sized child collections of random elements are particularly useful.
> Example of generating a multilevel, multilocale object and JSON document

- test/address.unit.js
- test/commerce.unit.js
- test/database.unit.js
- test/finance.unit.js
- test/helpers.unit.js
- test/image.unit.js
- test/internet.unit.js
- test/locales.unit.js
- test/lorem.unit.js
- test/music.unit.js
- test/name.unit.js
- test/random.unit.js
- test/system.unit.js
- test/unique.unit.js
- test/vehicle.unit.js
I've reviewed all test cases and change deprecated functions.
> Replacement of deprecated functions on tests.

- lib/iban.js
- test/finance_iban.unit.js
- test/finance_issue.unit.js
Adding a test to validate the correction of the issues
fix #944 GE IBAN
fix #945 PK IBAN
fix #946 TR IBAN
fix #846 AZ IBAN
> Fix for issues 846, 944, 945, 946 With TDD

- lib/index.js
- lib/system.js
> perf(system): improve commonFileName, commonFileExt, fileType, directoryPath performance

- build/gulp-tasks/package.js
- lib/finance.js
> Avoid ES6 syntax for now

- lib/locales/fr/name/female_first_name.js
Remove tailing quote on Mauricette
> Remove tailing quote

- locale/hr.js
I guess this file was created by copy pasting de.js and the locate in the class ctor was not changed to hr
> fix for copy paste error in hr.js
