lib/helpers.js
test/helpers.unit.js

Fix issue Marak/faker.js#214 with shuffle() sometimes inserting `undefined` into the shuffled array. 
Add a dubious spec that just asserts the proper usage of `faker.random.number()`.

Fix issue Marak/faker.js#214 with shuffle()

---

lib/random.js
test/random.unit.js

Also added tests for random.array_element
This fixes the same issue noted in [this pr](https://github.com/Marak/faker.js/pull/154)
However, it fixes it a different way.
I came across this issue initially when calling `faker.random.array_element` on an array of length 1.  Since the result of `faker.random.number({max:0})` was not being constrained correctly, the result of the aforementioned command would be `undefined`.

Fixing bug in random.number when max = 0

---

package.json

specifying the type and URL is deprecated:
https://docs.npmjs.com/files/package.json#license
http://npm1k.org/

Update license property

---

index.js
lib/company.js

The `company.suffixes` function was returning a hard-coded array of English suffixes. Modify it to return the suffixes provided in the locale file instead.

Make company suffix function use data from locale instead of hard-coded data

---

lib/internet.js
test/internet.unit.js

`faker.internet.mac()` generate a valid MAC Address with a sequence of six pairs of hexadecimals numbers separated by `:`

Adding a MAC Address generator

---

index.js
lib/name.js
test/all.functional.js
test/internet.unit.js
test/name.unit.js

I had to make a few concessions when doing this.
Ideally I would have added this function under the `company` module,
but I chose to add it to the `name` module instead,
as the data happened to already exist in the locale files under
`name.title`.
However, I felt that the field names in the locale files were confusing,
so their wrappers in the name module are renamed for clarity.
For example, `faker.name.jobArea()` returns a random element from
locale.name.title.level. In my opinion, 'jobArea' was a much better
description of the data than 'level'.
Finally, fixed a bug in one unit test which didn't restore a function
to its original state after watching it.
fixes #148

Add new jobTitle function to name object.

---

build/build/faker.js
index.js
lib/address.js
lib/helpers.js
lib/locales/en.js
lib/locales/en_CA.js

The intent of this was to address issue #126. In doing so, I have allowed for zip code formats to be locale based. Also, a user can now pass in their desired zip code format like:
`faker.address.zipCode("####");`
`faker.address.zipCode("?#? #?#");`
If no format is passed in, faker simply uses the format defined by the locale. 
Also, YT is the official abbreviation for Yukon. Reference: http://en.wikipedia.org/wiki/ISO_3166-2:CA.

Canadian zip codes (postal codes) now formatted properly. Better support for locale based zip code formats.

---

lib/internet.js

Eliminate cases when result is a number, in which case, replace does not exist.

Username must be a string

---

package.json

`through2` required by `buid/gulpfile.js` was missing.

through2 dependency added to devDependencies

---

lib/lorem.js

Partially addresses https://github.com/Marak/faker.js/issues/233. Sentences now start with a capital letter and end with a period. 
```js
faker.lorem.sentence()
// "Voluptatibus rerum non possimus similique ut consectetur aut provident."
```
Held off on changing the return types of `lorem.sentences` and `lorem.paragraphs` since thats a breaking change.

Fixed lorem.sentence formatting

---

lib/address.js
test/address.unit.js

When `streetSuffix()` returns an empty string, do not append a space to the end of the name part of `streetName()`. With the prior behavior, occasionally, `streetName()` would return something like `"Ashley "` (notice the trailing space), which is undesirable in many circumstances.

Only append suffix to streetName if suffix is present

---

lib/locales/sv/date/index.js
lib/locales/sv/date/month.js
lib/locales/sv/date/weekday.js
lib/locales/sv/index.js

Added support for Swedish months and weekdays, based on the english implementation.
I also excluded `wide_context` and `abbr_context` as they are optional according to the comments and there is no contextual difference in Swedish.

Added Swedish locale for date

---

lib/address.js

The citySuffix is a real word suffix (like "ton" or "burgh") so there should not be whitespace before it.
(The cityPrefix is a separate word (like "Lake" or "North"), so still needs whitespace.)

No space before citySuffix in city name

---

lib/internet.js

This fixes an issue when using exampleEmail in a fake template (e.g. {{name.exampleEmail}}).

Fix 'this' reference in exampleEmail

---

Readme.md

[docs] Fix a typo in Readme

---

lib/lorem.js

Fix typo in docstring for lorem.js. (separatora vs separator)

Fix typo in docstring

---

lib/finance.js

This simplifies the faker.finance.amount function a bit by avoiding arithmetic, and allows faker.random.number to do the heavy lifting with a precision operator. Fixes #361

Fix output of faker.finance.amount.

---

lib/system.js
test/system.unit.js

A number of the word lists contain "24/7" as a word, for example: https://github.com/Marak/faker.js/blob/e8231413cc38a3ce49d712823dadbffbd1849acc/lib/locales/en/company/bs_adjective.js#L17
This means that calling `faker.system.fileName()` or `faker.system.commonFileName()` could sometimes yield something like "some_words_24/7_yep.jpg". This implies a file called "7_yep.jpg" in a directory called "some_words_24", which is probably not what someone calling these methods wants.

Don't allow path seperators in generated filenames

---

build/src/docs.md

The docs are using a non-extant method at the moment.

Docs: `seed()` is on `faker`, not `random`.

---

.npmignore

In our company we use Docker containers for development. Once I checked size of Images and was amazed how 2 different Node application have 300 MB diff size. After some digging I found it is just in npm packages. One of then is this Faker.js
When checking size after npm install it give me this: 
```
du -hd0 node_modules/faker
74M    node_modules/faker
```
I decided to give it some time and check what can take so much I came with this. Adding `.npmignore` wont publish selected files to npm repository. It have many bonuses like saving network footprint to faster installation.
After adding `.npmignore` result is following:
```
du -hd0 node_modules/faker
9.3M    node_modules/faker
```
I tried to run tests on https://github.com/apiaryio/dredd which use this package and it works fine.
Of coure …

Add .npmignore to reduce size of package

---

lib/internet.js
test/internet.unit.js

A mac address can be of the following forms:
```
000CF15698AD
00:0C:F1:56:98:AD
00-0C-F1-56-98-AD
```
In my use case, I need to use `-`. 
I would like to add a `sep` parameter to allow the user to specify the mac separator. It will default to using `:` if none is provided.
I can add tests to this pull request, but wanted to validate if this approach works for you before I spend too much time on it.

Allow user to specify separator to be used in mac address

---

lib/locales/pl/name/first_name.js

I think this em-dash was separating the male and female names?  Its definitely not a good first name to suggest.  (I noticed when faker.internet.domainWord() returned this em-dash.)

Remove emdash from pl's first_name.js

---

Readme.md
lib/index.js

If you do `import * as faker from 'faker'` you can't do `faker.locale = 'uk';` since it produce runtime errors. 
ES6 forbids you to modify properties of top-level important objects and same is also true for TypeScrips.

Add 'setLocale' method to solve problem with ES6 import

---

lib/locales/pl/address/country.js

Ran schema & type-safety check over locales and found some obvious errors.
Mostly doing these checks in preparation of a new fast binary storage format for locales in [**Bogus** (C# port of faker.js)](https://github.com/bchavez/Bogus).
This removes the number `2008` found in `lib\locales\pl\address\country.js`.
:fallen_leaf: :leaves: **[Distance - Falling (ft Alys Be)](https://www.youtube.com/watch?v=WIfwIv4wNCE)**

Remove the number 2008 from pl/address/country.js

---

lib/company.js
test/company.unit.js

- re-orderes adjective and buzz in the company.bs template literal for a correct gramatics as sugessted in the issue #496,
- re-orders the statements in the unit test to reflect the same order as in the function for an easier read.

re-order of the company.bs adjective and buzz (#496)

---

lib/address.js
lib/index.js
lib/locales/en/address/direction.js
lib/locales/en/address/direction_abbr.js
lib/locales/en/address/index.js
test/address.unit.js

- `faker.address.direction()` returns random direction
- `faker.address.cardinalDirection()` returns cardinal direction (N/E/S/W)
- `faker.address.ordinalDirection()` returns ordinal direction (NE/NW/SE/SW)
includes unit tests
Addresses issue #457

add directions to Address namespace

---

.npmignore

don't npmignore build/build/faker.js or build/build/faker.min.js
even though we ignore the rest of build/*
I tested it locally using `npm pack`
Fixes https://github.com/Marak/faker.js/issues/575

don't npmignore build/build/faker.js 

---

vendor/unique.js

Note #466 and [my comment on times](https://github.com/Marak/faker.js/issues/466#issuecomment-357140244). Refreshes `startTime` at 0 loop depth, preventing scripts which last longer than 5 seconds from throwing.
BTW I needed to use a fork of `gulp-gh-pages` because [this PR](https://github.com/shinnn/gulp-gh-pages/pull/117) isn't merged, which fixes [this issue](https://github.com/shinnn/gulp-gh-pages/issues/116), which is currently breaking your gulp build :smile:

Reset startTime appropriately

---

lib/finance.js
test/finance.unit.js

The current `bitcoinAddress` generator version is returning invalid bitcoin addresses. The addresses consist of random digits and uppercase and lowercase letters, **with the exception** that the uppercase letter "O", uppercase letter "I", lowercase letter "l", and the number "0" are never used to prevent visual ambiguity. (https://en.bitcoin.it/wiki/Address)
This PR purposes a fix for this issue.
**Note**:
Travis failed to build my PR but I suspect it has nothing to do with the changes that I made:
```sh
npm ERR! Linux 4.9.6-040906-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.12.0/bin/node" "/home/travis/.nvm/versions/node/v6.12.0/bin/npm" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect
npm ERR! …
```

Fix bitcoinAddress generator

---

lib/date.js
test/date.unit.js

Closes #686
There might be more date functions that need updating, if so just let me know what I missed.

fix(date): Allow for `refDate` in `soon()`, `recent()`

---

lib/locales/en/company/bs_noun.js

Attempts to keep `faker.company.bsNoun()` hip and trendy by adding `blockchains` to the list of available nouns.
Example new `faker.company.bs()` output:
```
leading-edge facilitate blockchains
front-end cultivate blockchains
scalable maximize blockchains
extensible enhance blockchains
end-to-end deliver blockchains
visionary revolutionize blockchains
turn-key innovate blockchains
world-class enhance blockchains
intuitive optimize blockchains
viral transition blockchains
```

feat: add "blockchains" as a company.bs_noun

---

lib/finance.js
test/finance.unit.js

Ethereum addresses should be all lowercase.  Uppercase chars in ethereum addresses are a sort of optional checksum.  If a program is validating ethereum addresses, random capital letters in the hex string will cause the checksum to fail.

fix: lowercase eth addresses

---

lib/locales/nl_BE/address/city.js

Fixed an issue for the nl_BE locale. The City names get generated with a } between them if they're a compound of city_prefix and city_suffix.

Removed redundant } in nl_BE city names

---

lib/finance.js
test/finance.unit.js

How @amartiuz said on issue #884 , the function `faker.finance.amount()` was returning a `string` instead of a `number`, sometimes this can cause a problem and don't make sense the function returns a string. This PR fixes this.
Behavior before of this changes: returns a string. ie: "122.12"
Behavior after of this changes: returns a number. ie: 122.12

Fix return of finance.amount

---

lib/image.js

It could just be my ISP, but I have had a lot of trouble loading images from lorempixel.com. This changes the base url for the image request from lorempixel.com to placeimg.com, which share the same url structure when querying for random images.

Change image url to stable provider

---

CODE_OF_MERIT.MD

url to document  is wrong ( redirect to Mayan EDMS page)
The Code of Merit used to be mantained by its original author but he discontinued every one of his projects except for Mayan EDMS. This website is an attempt to keep the Code of Merit available.

Update code of merit url in CODE_OF_MERIT.MD

---

lib/address.js
lib/index.js
test/address.unit.js

Added `address.timeZone` with a simple test. Data was already there but the method was missing. Skipped doc generation because it was creating lots of noise(changes) in my machine.

Add Time Zone

---

lib/helpers.js
test/helpers.unit.js

There was a bug in the implementation of the modern Fisher–Yates
algorithm in that `i` was being decremented prematurely in each loop.
This caused the last element of the array to never be swapped
and therefore remain the last element.
Updated doc to denote the provided array is shuffled in place.

Bugfix random.shuffle last element.

---

lib/random.js

faker.random.word() has a bug where sometimes it returns a string with more than one word. This PR fixes that bug by splitting the previous result on spaces and selecting randomly from the words returned.
Fixes #661 
Fixes #602

Ensure faker.random.word does not return more than one word

---

lib/name.js
test/name.unit.js

Added a feature where you can pass a string into `faker.name.firstName(gender)` 
- Accepts "male" or "female" in English (all other strings fall back to non-gendered names)
- Case insensitive 
- Unit tests created for new inputs
Fixes #677

Allowed gender passed to name.firstName(gender) to be a string

---

lib/locales/fr/address/city_name.js

"Lille" is the real city name, not "Lille13".

fr/address/city_name.js: fix typo in "Lille" name

---

lib/finance.js
test/finance.unit.js

#773 
The new transaction description method on faker.finance will allow something like this
```
faker.finance.transactionDescription();
=> "deposit transaction at Jacobs, Tremblay and Gorczany using card ending with ***5331 for EGP 141.20 in account ***03287186"
```
successfully ran `gulp` and `mocha`
open for further improvements 👍🏻

add transaction description method on finance module

---

test/internet.unit.js

Proving it is not deterministic and does not respect random seed.
Previously reported and ignored.
- https://github.com/Marak/faker.js/issues/929
Issue appears to have been fixed by @starsprung in the following PR.
- https://github.com/Marak/faker.js/pull/924
Tested that this test is fixed by @starsprung's changes.
- https://github.com/joshua-barnett/faker.js/compare/bfe2c99...16cfc9f

Add failing test for userAgent

---

lib/locales/en/finance/currency.js

According to the following sources, STN is the ISO code of dobra:
* https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe_dobra
* https://www.xe.com/currency/stn-sao-tomean-dobra

correct dobra code and symbol

---

lib/finance.js
test/finance.unit.js

On issue #984, it was said that the function faker.finance.amount() was returning a number instead of a string. This PR fixes this.
Behavior before of this changes: returns a number. ie: 
```js
faker.finance.amount()
faker.finance.amount()
faker.finance.amount()
95.15
669.55
550.8
```
Behavior after of this changes: returns a string. ie:
```js
faker.finance.amount()
faker.finance.amount()
faker.finance.amount()
"95.15"
"669.55"
"550.80"
```

Fix return of finance.amount to string

---

lib/locales/nb_NO/name/index.js

`faker.name.findName()` was generating English first names and Norwegian last names, when nb_NO is specified as locale. I think this is due to the expected property names in lib/name.js. The Norwegian locale file uses `feminine_name` and `masculine_name`. Renaming the properties to `female_first_name` and `male_first_name` worked.
Can be reproed with:
```html
<!DOCTYPE html>
<html lang="">
<head>
<script src = "faker.js/dist/faker.js" type = "text/javascript"></script>
<script>
faker.locale = "nb_NO";
console.log(faker.name.findName())
</script>
<meta charset="utf-8">
<title>Testing Norwegian names</title>
</head>
<body></body>
</html>
```

Fix wrong naming of first name variables in the Norwegian locale

---

lib/internet.js
test/internet.unit.js

This pull request provides a convenient way to generate port numbers.
Linking the port number specification: https://tools.ietf.org/html/rfc6335#section-6

Add method to generate port numbers

---

examples/node/singleLocale.js
lib/helpers.js
test/internet.unit.js

Closes #943
This PR fixes the internet email for `ja` and `ch` locales, which was returning invalid emails.
Also, I fix the node examples because it had a wrong import path.

Fix: internet email for japanese and chinese characters

---

lib/finance.js
test/finance.unit.js

We have a few integration tests running where we need an IBAN from a specific country, but the `iban` method always returned a random one. 
This PR adds a second (optional) parameter to the `iban` method where you can pass the country from which you want to generate an IBAN

Add optional country code parameter for iban method

---

lib/locales/en/finance/currency.js

When building my app using Snowpack I noticed a warning related to a duplicate entry for "Indian Rupee" on `currency,js`. This PR removes the entry that doesn't include the curency symbol.
Snowpack output is below:
```
[snowpack] ✔ dependencies ready! [21.59s]
[snowpack] ! verifying build...
[snowpack] ✔ verification complete [0.02s]
[snowpack] ! writing build to disk...
[snowpack] ! optimizing build...
> _snowpack/pkg/faker.js: warning: Duplicate key "Indian Rupee" in object literal
42255 │   "Indian Rupee": {
╵   ~~~~~~~~~~~~~~
_snowpack/pkg/faker.js: note: The original "Indian Rupee" is here
42247 │   "Indian Rupee": {
╵   ~~~~~~~~~~~~~~
1 warning
[
{
detail: undefined,
location: {
column: 2,
file: '_snowpack/pkg/faker.js',
length: 14,
line: 42255,
lineText: '  "Indian Rupee": {'
}, …
```

Fix: remove duplicate key for "Indian Rupee" on currency.js

---

lib/finance.js
test/finance.unit.js

✅ Closes: #1108 
* Remove multiple calls to `createTransaction` from within the `finance.transactionDescription` method and instead reference the required values from the returned transaction object.
* Provide the unit test(s) for the code change.
After the change I ensured that:
* all tests are passing, by running `npm run test`,
* formating / code style is consistent.

[Improvement] Call `createTransaction` method once from within `finance.transactionDescription`

---

lib/random.js

`faker.random.arrayElements` has performance issues when dealing with large arrays.
The following implementation significantly improves performance.
Performance tests for an array of 200000 items:
| Count  | Old implementation | New implementation |
| -      | -                  | -                  |
| 20000  |      1872ms        |       10ms         |
| 40000  |      1643ms        |       9ms          |
| 60000  |      1542ms        |       9ms          |
| 80000  |      1429ms        |       10ms         |
| 100000 |      1270ms        |       12ms         |
| 120000 |      1099ms        |       15ms         |
| 140000 |      1013ms        |       25ms         |
| 160000 |      623ms         |       23ms         |
| 180000 |      333ms         |       22ms         |
Performance tests …

Improve faker.random.arrayElements performance

---

lib/datatype.js
lib/index.js
lib/mersenne.js
lib/random.js
test/random.unit.js
test/support/function-helpers.js
vendor/mersenne.js

> fixes #768 
Currently, every Faker instance shares the same random number generator instance which means that to seed one faker instance is to seed them all. This is also a pre-requisite for #318 (see https://github.com/Marak/faker.js/issues/318#issuecomment-369658181)
This just extracts the public API of the mersenne twister found in `vendor/mersenne.js` and creates a single instance of it per faker.
This implementation is a tad sub-optimal since calling `seed()` on a faker instance will result in two redundant calls to `mersenne.init_genrand()`: one in `random.js` and the other in `datatype.js`. It would probably be more DRY to create the mersenne instance once in faker and then pass it into to the `Random` and `Datatype` instances, however, this takes the strategy of the smallest …

Give each faker instance its own random number generator

---

Readme.md

I couldn't find a makefile to run `make test` so I've updated the README.md to include `npm run test` which successfully runs the tests as defined in package.json [here](https://github.com/Marak/faker.js/blob/e073ace19cbf68857a5731dc3302fda0eb36cf24/package.json#L17).

Update README about running tests

---

Readme.md

Seeing deprecation messages when trying to use faker.random.x -- Do we need any other updates, perhaps here as well?   http://marak.github.io/faker.js/

Remove deprecated "random" entries from Readme.md

---

lib/internet.js
test/internet.unit.js

Fixes #1181. The idea to use the same randomness as docker uses for container names. This choice gives 1349 * 6804 choices = 9178596 choices

change domainWord generation algorithm to <adjective>-<noun>
